### ISSUE TITLE
[BUG] Linked with alias has some issue

### ISSUE THREAD

**Issue by Gourav1910** [pvojtechovsky/obsidian-link-with-alias#15]
Hi when I select any text and press my hotkey for the command link with alias (when the same text is note copied before `|` this symbol) then it put a character `[[̥` you can see it here. Then I have backspace one time to clear that character and then start typing my note name. If I don't do backspace then it also include that character as first character of my note search and hence I can't find any note because I don't have any note with that character.

![image](https://github.com/pvojtechovsky/obsidian-link-with-alias/assets/101202140/e27872f2-f07a-43f1-a01b-ee692202d779)
You can see it in screenshot. My selected text was "shraddha" and I write the text before this `|` symbol was "Shraddha" but without backspacing that character and hence it put that circle like character below the first character of my inserted text. And it is not a seperate character but it is attached to first letter of my word. Please fix this issue.

**Comment by pvojtechovsky** [comment]
@Gourav1910 
I need more information, otherwise I will close this issue as not reproducible at the end of this year.
