### ISSUE TITLE
[FEATURE REQUEST] Display the link name as an alias

### ISSUE THREAD

**Issue by jsrdcht** [pvojtechovsky/obsidian-link-with-alias#17]
There is currently no plugin available to achieve this feature, and the current links will be displayed as file names by default.
We hope that obsidian-link-with-alias can achieve this functionality.

**Comment by pvojtechovsky** [comment]
@jsrdcht I do not understand this request. Could you provide some example and screenshot?

**Comment by pvojtechovsky** [comment]
@jsrdcht This request is not understandable for me. Provide more information please or I will close it end of this year.
