### ISSUE TITLE
[Question] How does it compare to the plugin obsidian-note-aliases?

### ISSUE THREAD

**Issue by berot3** [pvojtechovsky/obsidian-link-with-alias#4]
This is the link: https://github.com/pulsovi/obsidian-note-aliases

It is already accepted btw.

**Comment by pvojtechovsky** [comment]
Both plugins behave same when command is started on the existing link. They both create an alias in link target note.

While purpose of [obsidian-note-aliases](https://github.com/pulsovi/obsidian-note-aliases) is actually only to create an alias of existing link, the purpose of my [obsidian-link-with-alias](https://github.com/pvojtechovsky/obsidian-link-with-alias) plugin is to cover whole link creation process (including adding link brackets, adding separator between link name and link text and adding alias).

My plugin is optimized for the cases when user needs to create a lot of links. There are these extra features:
* It keeps the origin text. Note: standard obsidian link autocompletion can change the origin link text, which is not wanted in my case. I want to keep text as it is, just to add links.
* Minimize necessary effort. It means, just select the text which has to be converted to the link, run the command, select the target and press enter. Or in some cases you have to type in the part of the target note name, before you press Enter to finish link and alias creation.
* The created aliases are sorted from longest to shortest, which is necessary to have other other Obsidian features working well.

You can see most of the use cases on [README](https://github.com/pvojtechovsky/obsidian-link-with-alias/blob/main/README.md) page.

**Comment by berot3** [comment]
Thanks a lot, this sounds awesome!
