### ISSUE TITLE
[FEATURE REQUEST] Reverse Modification

### ISSUE THREAD

**Issue by lgamtj** [pvojtechovsky/obsidian-link-with-alias#5]
**Is your feature request related to a problem? Please describe.**
Is it possible to add the feature of reverse modification? 
When an alias is updated in the YAML, can those links in other documents that reference the updated alias be updated automatically?

**Comment by pvojtechovsky** [comment]
It is an interesting idea, but in order to understand you deeper and to implement the best solution, I would like to understand the story which is behind this feature request. Could you give me some story like: 
> I created 50 pages which are linked together and I am using aliases in these links. One of these aliases is word "car", but I found that it is better for understanding of my readers to use work "automobile" instead. Now I want to replace all occurrences of [[NameOfNoteWithCar|car]] by [[NameOfNoteWithCar|automobile]] in whole vault.

**Comment by pvojtechovsky** [comment]
@lgamtj any update?
