### ISSUE TITLE
[FEATURE REQUEST] Support of mobile

### ISSUE THREAD

**Issue by safrilth** [pvojtechovsky/obsidian-link-with-alias#6]
i was really excited when this plugin launched

I tried it on my mobile phone, but it doesn't support it yet.

I just want to ask if in the future you will support the plugin for obsidian mobile app?

**Comment by pvojtechovsky** [comment]
I haven't tried it on mobile, there is a good chance that it works too. It has to be tested ... 
If there is any volunteer which would test it and report problems or tell me that it works so I can enable support of mobile too, then it would help.
May be I will try it too in future, but actually I am not using obsidian on mobile, so I have no clue...
Any idea how to proceed here?

**Comment by pvojtechovsky** [comment]
I just tried it my mobile and forced my plugin to load there and seems to be working. The only problem I see now is that plugin command is missing the icon and that I have to enable support for mobile. I will do it soon :-) It seems to be a little effort which can help others a lot, so it makes sense

**Comment by pvojtechovsky** [comment]
The support of mobile devices was added in version 1.0.3
