### ISSUE TITLE
[FEATURE REQUEST] Referring note without making it alias in the frontmatter

### ISSUE THREAD

**Issue by Gourav1910** [pvojtechovsky/obsidian-link-with-alias#9]
Hi your plugin is amazing. I want you to add one more feature with a command(so that we can make it hotkey). Here when we select a text and press our hotkey then it should refer to the note life to connect the selected text where we can just start typing our note name and enter to connect that note to the selected text. Right now when we select our text and press the hotkey then it also write that text before this symbol "|". I want that place to be empty so that we can just start typing our note name and connect it as fast as possible. And the main thing that I am asking is that in this command it should not create alias because suppose if I say in any note that "refer to this note" and if I linked my note to "this" so I don't want "this" as alias. But I want to connect my any note as fast as possible to any selected text which I think your plugin can do it.

**Comment by pvojtechovsky** [comment]
Hi, do I understand well that you ask for new command which will do the same like existing command with these exceptions:
* the text selected before the command was executed is not copied before the `|` path and link display text separator. It stays as display text separator. So it looks like this `[[|selected text]]`
* the editor cursor is located after `[[` and before `|` so you can start to type target note name
* the alias is not created in the target note for the display text. 
So we just make a link around selected text. That is all.

Correct?

**Comment by Gourav1910** [comment]
> 

Yes exactly this is what I want😊🫠. Is it possible? Because it will be very useful to quickly connect our note with any selected text.

**Comment by pvojtechovsky** [comment]
@Gourav1910 
I implemented something similar in v 1.0.5
Part of the feature you ask for is added as configuration. I did not liked to have 4 commands 
* link with alias and copied text
* link with alas and not copied text
* link with copied text
* link without copied text

So now there are these commands:
* Link with alias
* Link
where coping of text is configurable.

If you need it different then I would like to understand the use case, which needs that.

**Comment by Gourav1910** [comment]
> @Gourav1910 I implemented something similar in v 1.0.5 Part of the feature you ask for is added as configuration. I did not liked to have 4 commands
> 
> * link with alias and copied text
> * link with alas and not copied text
> * link with copied text
> * link without copied text
> 
> So now there are these commands:
> 
> * Link with alias
> * Link
>   where coping of text is configurable.
> 
> If you need it different then I would like to understand the use case, which needs that.

As I told you in previous replies that it would make linking notes faster. Right now we have to select text then put double bracket then this symbol `|` and then we have to bring cursor at right position and then we start typing the name of note we want to link but with that command we will just select text and press hot key and then just start typing note name and link it. So the reason is fast linking. If you don't wanna add too many commands then atleast you can leave an option in the plugin setting to turn on this command if you need so in that way only people who need that feature will turn on it in settings.

**Comment by pvojtechovsky** [comment]
> you can leave an option in the plugin setting to turn on this command if you need so in that way only people who need that feature will turn on it in settings.

I understood your origin request, it makes sense for me too. The required setting was already added in version 1.0.5 :-)

I just wander whether there is an user who would need two commands like:
* create link with alias and copy text into link name
* create link without alias and with empty link name
Because that is actually not supported without change of settings.

**Comment by pvojtechovsky** [comment]
> Because I don't understand the point of that text if we want to link that with other note
The purpose of that text is that in 80% (in case of my vault) it fuzzy fits to target note, so Obsidian link autocompletion offers it and you can just press Enter, without typing anything. When text is not fitting, then I delete it and write what I want, ... but that happens in my case only rarely.

Anyway it is already released so you can try it, just update the plugin in obsidian.

**Comment by Gourav1910** [comment]
> > Because I don't understand the point of that text if we want to link that with other note
> > The purpose of that text is that in 80% (in case of my vault) it fuzzy fits to target note, so Obsidian link autocompletion offers it and you can just press Enter, without typing anything. When text is not fitting, then I delete it and write what I want, ... but that happens in my case only rarely.
> 
> Anyway it is already released so you can try it, just update the plugin in obsidian.

Ok thankyou so much I just checked that you have updated it. I don't know whether you did it before my reply or after but thankyou. I got what I wanted🥰🥳🥳.

**Comment by Gourav1910** [comment]
Just last thing to say instead of `[[text|text]]` if you make it `[[Text|text]]` so i think it will me more useful because people usually want to make the note which start with capital letter. So while writing if they immediately wanna make note of any text and if that text is starting with small letter then they can immediately make it a note but the note name will start with capital letter. I mean they still can edit it but it is about convenience. Ok thankyou for all your replies🙏🙏.

**Comment by pvojtechovsky** [comment]
> link name with uppercase first letter

Good idea. It makes sense in m use case too. I will make it in next release

**Comment by Gourav1910** [comment]
> > link name with uppercase first letter
> 
> Good idea. It makes sense in m use case too. I will make it in next release

Can't you also make it as an optional third command in setting to toggle on and off because now I have to choose between this option where text is already written vs where text is not written. Is it possible a setting which make it avail both type of option if someone want they will turn it on. I mean if your plugin is not become too heavy in code which I don't know about.

**Comment by pvojtechovsky** [comment]
I can imagine that link creation on mobile phone is better without copying text, so user always types in the link name, which is probably faster because deleting the link name on mobile can be quite complicated.

But I cannot imagine that some user will choose between two commands (copy/don't copy text) depending the link already exists and link name is different then link text.

I would like to wait for feedback of users who use it for some time and to make plugin configuration more complex only in the case it is realy needed and helpful....because more complex settings will bother every client and will make documentation complex and trick for all clients. It also brings risk that unexperience clients will use wrong settings and have bad experience.

So I prefer to keep it simple for now.

**Comment by Gourav1910** [comment]
ok thanks for clarifying😊

**Comment by pvojtechovsky** [comment]
> Make the selected text's first letter in capital so that note name would be start with capital letter and the text in other note remains start with small letter because it is in middle of line.

This feature is implemented in release version 1.0.6

I suggest to close this feature request. If you have other ideas, then make new issues please. It is easier to handle small issues than long one with many ideas.
